### ISSUE TITLE
MinHeap and MaxHeap realisations are broken

### ISSUE THREAD

**Issue by Boiarshinov** [TheAlgorithms/Java#3158]
MinHeap and MaxHeap implementation are broken. 
Instance of these heaps couldn't be instanciated with any not empty list of elements.

Here is a test code to reproduce:
```java
@Test
void createFromList() {
    var elements = List.of(
            new HeapElement(5)
    );
    MaxHeap heap = new MaxHeap(elements);
    //similar with MinHeap
}
```

Stacktrace:
```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1

	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.thealgorithms.datastructures.heaps.MaxHeap.getElementKey(MaxHeap.java:46)
	at com.thealgorithms.datastructures.heaps.MaxHeap.toggleUp(MaxHeap.java:59)
	at com.thealgorithms.datastructures.heaps.MaxHeap.insertElement(MaxHeap.java:97)
	at com.thealgorithms.datastructures.heaps.MaxHeap.<init>(MaxHeap.java:20)
```

**Comment by Boiarshinov** [comment]
This issue could be **good_first_issue** for newcomers. I'm not pretend to solve it by myself 😄

**Comment by Jainam1401** [comment]
@siriak Thanks for assigning me the issue. Can you please help me know this issue better and steps I need to follow to make contribution?

**Comment by siriak** [comment]
You need to make a fork of this repo, then make changes in it, and then make a pull request from your fork to this repo

**Comment by Jainam1401** [comment]
@siriak Thanks for the help.

**Comment by alexsikorski** [comment]
Hi guys, could you please assign me as well?
