### ISSUE TITLE
Test Cases for crypto/hash/Sha2.java are failing due to OutOfMemory error

### ISSUE THREAD

**Issue by abhijay94** [TheAlgorithms/Java#768]
I tried the running GUnits in src.test.java.com.crypto.hash.Sha2Test and the test cases get ignored because of the following error:
`java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
	at java.lang.StringCoding.encode(StringCoding.java:344)
	at java.lang.StringCoding.encode(StringCoding.java:387)
	at java.lang.String.getBytes(String.java:958)
	at src.test.java.com.crypto.hash.Sha2Test.setUpClass(Sha2Test.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)`

I tried running the test with a massive maximum heap size of 20GB and still got the same error. Is there a possible memory leak in the test case? 

Here are the JVM arguments I used for the test case
`-ea -Xms12G -Xmx20G -XX:+UseCompressedOops`

@yanglbme I was running all the tests in the project along with code coverage and this is the only test which seems to be failing.

**Comment by yanglbme** [comment]
Hi @abhijay94 

 I've removed the test case which causes OOM error, and now it's ok.
